name: Github Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: ['.github/**']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "🧪🧪🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "🧪🧪🧪 Load-Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "🚀 Step 1 of many xD..."
          sleep 10
      - run: |
          echo "🚀 Step 2 av 2, neida hehe..."
          sleep 10
      - run: |
          echo "🚀 Step 3 av Tre..."
          sleep 10
      - run: |
          echo "🚀 Step 4 av 1 hahaha..."
          sleep 10
      - run: |
          echo "🚀 Step 5 neida bro..."
          sleep 10
